{% set name = "StitchM" %}
{% set version = "1.2.1" %}
{% set import_name = "stitch_m" %}
package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://github.com/DiamondLightSource/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: c58264deb226d872b073b6c90e1fd304f21b3f07fff72a45fee9a336d29c92f2

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - {{ name }} = {{ import_name }}.scripts.commandline:main
  skip: true  # [py<37]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy >=1.17.4
    - tifffile >=2020.9.30
    - mrcfile >=1.1.2
    - omexml-dls >=1.0.3
    - pywin32  # [win]

test:
  imports:
    - {{ import_name }}
    - win32com.client  # [win]
  source_files:
    - src/tests
  commands:
    - python -m unittest discover -s src -p "test_*.py" -vv

about:
  home: https://github.com/DiamondLightSource/{{ name }}
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Stitches mosaic images from Cockpit (Micron)

  description: |
    StitchM stitches together mosaic images taken in Cockpit (Micron)
    into a universally readable format, currently .ome.tiff.
    The current output is an 16bit greyscale image when stitching the mosaic.
    Markers exported from Cockpit can be added as rectangular ROIs within the OME
    metadata stored in the image header. ROIs can be imported and displayed using
    bioformats in FIJI/ImageJ.
    Mainly for command-line use.
  doc_url: https://github.com/DiamondLightSource/{{ name }}/blob/master/README.md
  dev_url: https://github.com/DiamondLightSource/{{ name }}

extra:
  recipe-maintainers:
    - thomasmfish
